"""make_full_name_required

Revision ID: 0613b4db2eb2
Revises: f158ab26cd2e
Create Date: 2025-11-18 07:46:31.979269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0613b4db2eb2'
down_revision: Union[str, Sequence[str], None] = 'f158ab26cd2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First, update any existing NULL values to use username as fallback
    op.execute("UPDATE users SET full_name = username WHERE full_name IS NULL")
    # Then make the column NOT NULL
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
