"""add username to users

Revision ID: 33c1f11195d2
Revises: 2a2a4feb2fdb
Create Date: 2025-11-17 13:20:41.784967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c1f11195d2'
down_revision: Union[str, Sequence[str], None] = '2a2a4feb2fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'users',
        sa.Column('username', sa.String(length=255), nullable=True)
       )
    op.execute("UPDATE users SET username = email WHERE username IS NULL")
    op.alter_column('users', 'username', nullable=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
